/* HSHS Trending: real Firestore content only. */
import { firestore, storage } from './config.js';
import { collection, getDocs, limit, orderBy, query, where } from 'https://www.gstatic.com/firebasejs/12.15.0/firebase-firestore.js';
import { ref, getDownloadURL } from 'https://www.gstatic.com/firebasejs/12.15.0/firebase-storage.js';

const PAGE_SIZE = 9;
const CACHE_TTL = 5 * 60 * 1000;
const WEIGHTS = { engagement: 4, likes: 2, views: 1 };
const state = { period: 'week', filter: 'all', posts: [], page: 1, hasMore: true, cache: new Map() };
const $ = id => document.getElementById(id);
const esc = v => String(v ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const num = v => Number.isFinite(Number(v)) ? Number(v) : 0;
const debounce = (fn, ms=220) => { let t; return (...a) => { clearTimeout(t); t=setTimeout(()=>fn(...a),ms); }; };

function periodStart(period) { const d=new Date(); if(period==='today') d.setHours(0,0,0,0); else d.setDate(d.getDate()-(period==='month'?30:7)); return d; }
function dateValue(v) { return v?.toDate ? v.toDate() : new Date(v || 0); }
function ago(d) { const s=Math.max(1,Math.floor((Date.now()-d.getTime())/1000)); const u=[['day',86400],['hour',3600],['minute',60]]; const m=u.find(x=>s>=x[1]); return m ? `${Math.floor(s/m[1])} ${m[0]}${Math.floor(s/m[1])>1?'s':''} ago` : 'just now'; }
async function mediaURL(v='') { if(!v || !storage || !v.startsWith('gs://')) return v; try{return await getDownloadURL(ref(storage,v));}catch{return '';} }
async function normalize(docSnap) { const d=docSnap.data(); const likes=num(d.likesCount ?? d.likes), comments=num(d.commentsCount ?? d.comments), views=num(d.viewsCount ?? d.views), shares=num(d.sharesCount ?? d.shares); const p={id:docSnap.id,title:d.title||'Untitled post',description:d.description||'',mediaURL:await mediaURL(d.mediaURL||d.thumbnailURL||d.imageUrl||''),mediaType:d.mediaType||'image',category:d.category||'General',author:d.author||d.authorName||'HSHS Student',authorPhoto:d.authorPhoto||'',timestamp:dateValue(d.timestamp||d.createdAt),likesCount:likes,commentsCount:comments,viewsCount:views,sharesCount:shares,featured:Boolean(d.featured)}; p.engagementCount=likes+comments+shares; p.trendingScore=p.engagementCount*WEIGHTS.engagement+likes*WEIGHTS.likes+views; return p; }
function cacheGet(k){const x=state.cache.get(k);return x&&Date.now()-x.time<CACHE_TTL?x.data:null;}
function cacheSet(k,data){state.cache.set(k,{data,time:Date.now()});}
async function getPosts(period=state.period){const k=`trending:${period}`;const hit=cacheGet(k);if(hit)return hit;const q=query(collection(firestore,'posts'),where('timestamp','>=',periodStart(period)),orderBy('timestamp','desc'),limit(60));const s=await getDocs(q);const data=(await Promise.all(s.docs.map(normalize))).filter(p=>p.mediaURL||p.title);data.sort((a,b)=>b.trendingScore-a.trendingScore||b.timestamp-a.timestamp);cacheSet(k,data);return data;}
export async function getTrendingPosts(period=state.period){return getPosts(period);}
export async function searchTrendingPosts(text){const q=String(text||'').trim().toLowerCase();if(q.length<2)return [];return getPosts(state.period).then(ps=>ps.filter(p=>[p.title,p.description,p.category,p.author].some(x=>x.toLowerCase().includes(q))).slice(0,8));}
export async function getTopCategories(){const ps=await getPosts(state.period),m=new Map();ps.forEach(p=>{const x=m.get(p.category)||{name:p.category,postsCount:0,engagement:0};x.postsCount++;x.engagement+=p.engagementCount;m.set(p.category,x);});return [...m.values()].sort((a,b)=>b.engagement-a.engagement);}
export async function getTopLikedPosts(){return (await getPosts()).slice().sort((a,b)=>b.likesCount-a.likesCount).slice(0,5);}
export async function getTopViewedPosts(){return (await getPosts()).slice().sort((a,b)=>b.viewsCount-a.viewsCount).slice(0,5);}
export async function getTopCommentedPosts(){return (await getPosts()).slice().sort((a,b)=>b.commentsCount-a.commentsCount).slice(0,5);}

function media(p,small=false){ if(!p.mediaURL)return `<div class="feed-media"><div class="empty-state"><span>✨</span></div></div>`; return p.mediaType==='video' ? `<div class="feed-media"><video class="feed-image" preload="metadata" muted playsinline poster="${esc(p.mediaURL)}"><source src="${esc(p.mediaURL)}"></video><span class="play-icon"><i class="fas fa-play"></i></span></div>` : `<div class="feed-media"><img class="feed-image" src="${esc(p.mediaURL)}" alt="${esc(p.title)}" loading="lazy"></div>`; }
function avatar(p){return p.authorPhoto?esc(p.authorPhoto):'';}
function card(p,i){return `<article class="trend-feed-card" data-post-id="${esc(p.id)}"><div class="feed-media">${p.mediaURL?(p.mediaType==='video'?`<video class="feed-image" preload="metadata" muted playsinline poster="${esc(p.mediaURL)}"><source src="${esc(p.mediaURL)}"></video><span class="play-icon"><i class="fas fa-play"></i></span>`:`<img class="feed-image" src="${esc(p.mediaURL)}" alt="${esc(p.title)}" loading="lazy">`):'<div class="empty-state"><span>✨</span></div>'}<span class="feed-rank">#${i+1}</span></div><div class="feed-body"><span class="feed-category">${esc(p.category)}</span><h3>${esc(p.title)}</h3><div class="author-row">${avatar(p)?`<img src="${avatar(p)}" alt="">`:''}<div><span>${esc(p.author)}</span><small>${ago(p.timestamp)}</small></div></div><div class="feed-bottom"><span>❤️ ${p.likesCount} · 💬 ${p.commentsCount} · 👁 ${p.viewsCount}</span><strong>🔥 ${p.trendingScore}</strong></div></div></article>`;}
function topCard(p,rank,hero=false){if(!p)return '';return `<article class="${hero?'hero':'mini'}-trending-card" data-post-id="${esc(p.id)}"><div class="${hero?'hero':'mini'}-media">${p.mediaURL?(p.mediaType==='video'?`<video class="${hero?'hero':'mini'}-image" muted playsinline preload="metadata" poster="${esc(p.mediaURL)}"><source src="${esc(p.mediaURL)}"></video>`:`<img class="${hero?'hero':'mini'}-image" src="${esc(p.mediaURL)}" alt="${esc(p.title)}" loading="lazy">`):'<div class="empty-state"><span>✨</span></div>'}</div><div class="${hero?'hero':'mini'}-overlay"></div><span class="rank-badge ${rank===1?'rank-one':rank===2?'rank-two':'rank-three'}">#${rank}</span><div class="${hero?'hero':'mini'}-content"><span class="${hero?'top-label':'mini-category'}">${esc(p.category)}</span><h${hero?'2':'3'}>${esc(p.title)}</h${hero?'2':'3'}>${hero?`<p>${esc(p.description.slice(0,180))}</p>`:''}<div class="author-row"><span>${esc(p.author)}</span><small>${ago(p.timestamp)}</small></div><div class="trend-stats"><span class="likes">❤️ ${p.likesCount}</span><span>💬 ${p.commentsCount}</span><span>👁 ${p.viewsCount}</span><span>🔥 ${p.trendingScore}</span></div></div></article>`;}
function message(el,text,icon='✨'){if(el)el.innerHTML=`<div class="empty-state"><span>${icon}</span><h3>${esc(text)}</h3><p>Check back soon for more HSHS School Gallery moments.</p></div>`;}
function renderTop(){const hero=$('topTrendingHero'),side=$('topTrendingSide');if(!hero||!side)return;const ps=state.posts.slice(0,3);if(!ps.length){message(hero,'No trending posts yet');side.innerHTML='';return;}hero.innerHTML=topCard(ps[0],1,true);side.innerHTML=topCard(ps[1],2)+topCard(ps[2],3);}
function renderGrid(){const grid=$('trendingGrid');if(!grid)return;let ps=state.posts;if(state.filter!=='all')ps=ps.filter(p=>state.filter==='video'?p.mediaType==='video':state.filter==='image'?p.mediaType!=='video':state.filter==='buzz'?/buzz|short|clip/i.test(`${p.category} ${p.title} ${p.description}`):/event|sports|assembly|function/i.test(`${p.category} ${p.title} ${p.description}`));const shown=ps.slice(0,state.page*PAGE_SIZE);state.hasMore=shown.length<ps.length;if(!shown.length){message(grid,'No trending content for this filter');return;}grid.innerHTML=shown.map(card).join('');}
function renderInsights(){Promise.all([getTopCategories(),getTopLikedPosts(),getTopViewedPosts(),getTopCommentedPosts()]).then(([cats,liked,viewed,commented])=>{const c=$('topCategoriesGrid'),hot=$('hotTopics');if(c)c.innerHTML=cats.length?cats.slice(0,6).map(x=>`<div class="category-row"><span>🔥 ${esc(x.name)}</span><strong>${x.postsCount} posts</strong></div>`).join(''):'';if(hot)hot.innerHTML=cats.slice(0,8).map(x=>`<article class="hot-topic"><strong>#${esc(x.name)}</strong><span>${x.postsCount} posts</span><small>${x.engagement} engagement</small></article>`).join('');const list=(id,ps,key,icon)=>{const el=$(id);if(el)el.innerHTML=ps.length?ps.map((p,i)=>`<li class="leaderboard-item"><b>#${i+1}</b>${p.mediaURL?`<img src="${esc(p.mediaURL)}" alt="" loading="lazy">`:''}<span>${esc(p.title)}</span><strong>${icon} ${p[key]}</strong></li>`).join(''):'';};list('topLikedList',liked,'likesCount','❤️');list('topViewedList',viewed,'viewsCount','👁');list('topCommentedList',commented,'commentsCount','💬');}).catch(e=>console.warn('[HSHS] Trending insights failed',e));}
async function load(period=state.period){state.period=period;state.page=1;state.posts=[];state.hasMore=true;const grid=$('trendingGrid');if(grid)grid.innerHTML=Array.from({length:6},()=>'<div class="trend-skeleton"></div>').join('');try{state.posts=await getPosts(period);renderTop();renderGrid();renderInsights();}catch(e){console.error('[HSHS] Trending load failed',e);message(grid,'Trending content could not be loaded','⚠️');}}
function wire(){const period=$('periodSelect');if(period&&!period.dataset.wired){period.dataset.wired='1';period.addEventListener('change',()=>load(period.value));}const filters=document.querySelector('.trending-filters');if(filters&&!filters.dataset.wired){filters.dataset.wired='1';filters.addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;state.filter=b.dataset.filter;filters.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x===b));renderGrid();});}const view=$('viewAllTrending');if(view&&!view.dataset.wired){view.dataset.wired='1';view.addEventListener('click',e=>{e.preventDefault();state.filter='all';document.querySelectorAll('[data-filter]').forEach(x=>x.classList.toggle('active',x.dataset.filter==='all'));state.page=Math.max(1,state.page+1);renderGrid();});}const search=$('searchInput'),results=$('searchResults');if(search&&results&&!search.dataset.wired){search.dataset.wired='1';search.addEventListener('input',debounce(async()=>{const ps=await searchTrendingPosts(search.value);results.innerHTML=ps.map(p=>`<button class="search-result" data-post-id="${esc(p.id)}"><strong>${esc(p.title)}</strong><small>${esc(p.category)} · 🔥 ${p.trendingScore}</small></button>`).join('');results.classList.toggle('show',ps.length>0);},200));}if(!window.__hshsTrendingScroll){window.__hshsTrendingScroll=true;window.addEventListener('scroll',debounce(()=>{if(state.hasMore&&window.innerHeight+window.scrollY>=document.body.offsetHeight-650){state.page++;renderGrid();}},120));}}
function boot(){if(!$('trendingGrid'))return;wire();load(state.period||'week');}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
document.addEventListener('hshs:page',()=>setTimeout(boot,0));
window.startTrending=boot;