import { db } from "./db.js";
import { updateDoc, doc, increment } from "https://www.gstatic.com/firebasejs/12.15.0/firebase-firestore.js";
import { firestore } from "./config.js";

class VideosPage {
 constructor(){this.videos=[];this.filtered=[];this.index=0;this.filter="all";this.init()}
 async init(){this.bindFilters();this.bindPlayer();await this.load()}
 async load(){const c=document.getElementById("videosContainer");if(!c)return;try{this.videos=await db.getVideos(12,0)||[];this.apply()}catch(e){console.error(e);c.innerHTML=`<div class="empty-state"><h3>Unable to load videos</h3><p>${this.escape(e.message)}</p></div>`}}
 apply(){let a=[...this.videos],f=this.filter;if(f==="latest")a.sort((x,y)=>this.date(y.createdAt)-this.date(x.createdAt));else if(f==="trending")a.sort((x,y)=>this.score(y)-this.score(x));else if(f!=="all")a=a.filter(v=>String(v.category||"").toLowerCase().replace(/\s+/g,"-")===f);this.filtered=a;this.render()}
 render(){const c=document.getElementById("videosContainer"),hero=document.getElementById("featuredVideo"),count=document.getElementById("videoCount"),title=document.getElementById("videoSectionTitle");if(!c)return;if(!this.filtered.length){if(hero)hero.innerHTML="";c.innerHTML=`<div class="empty-state"><i class="fas fa-video"></i><h3>No videos yet</h3><p>Upload the first HSHS video!</p></div>`;if(count)count.textContent="0 videos";return}const [first,...rest]=this.filtered;if(hero)hero.innerHTML=this.card(first,true,0);c.innerHTML=rest.map((v,i)=>this.card(v,false,i+1)).join("");if(count)count.textContent=`${this.filtered.length} video${this.filtered.length===1?"":"s"}`;if(title)title.textContent=this.filter==="trending"?"Trending Videos":this.filter==="latest"?"Latest Videos":"Video Library";document.querySelectorAll("[data-video-index]").forEach(el=>el.onclick=()=>this.play(Number(el.dataset.videoIndex)))}
 card(v,featured,i){return `<article class="${featured?"featured-video":"video-card"}" data-video-index="${i}"><div class="video-thumbnail"><img src="${this.attr(v.thumbnailUrl||"")}" alt="${this.attr(v.title||"HSHS video")}" class="thumbnail-image" loading="${featured?"eager":"lazy"}">${featured?'<span class="featured-badge"><i class="fas fa-star"></i> FEATURED</span><span class="featured-play"><i class="fas fa-play"></i></span>':'<span class="play-button-overlay"><i class="fas fa-play"></i></span>'}<span class="video-duration">${this.escape(v.duration||"00:00")}</span></div><div class="video-info"><div class="video-title">${this.escape(v.title||"Untitled video")}</div><div class="video-description">${this.escape(v.description||"")}</div><div class="video-metadata"><span>${this.escape(v.author||"HSHS Student")}</span><span>${this.formatDate(v.createdAt)}</span></div><div class="video-stats"><span class="stat-item"><i class="fas fa-eye"></i>${this.num(v.views)}</span><span class="stat-item"><i class="fas fa-heart"></i>${this.num(v.likes)}</span><span class="stat-item"><i class="fas fa-comment"></i>${this.num(v.comments)}</span></div></div></article>`}
 bindFilters(){document.querySelectorAll(".video-tab").forEach(t=>t.addEventListener("click",()=>{document.querySelectorAll(".video-tab").forEach(x=>x.classList.remove("active"));t.classList.add("active");this.filter=t.dataset.filter||"all";this.apply()}))}
 bindPlayer(){const m=document.getElementById("videoPlayerModal"),p=document.getElementById("videoPlayer");document.getElementById("playerClose")?.addEventListener("click",()=>{p?.pause();m?.classList.remove("active")});m?.addEventListener("click",e=>{if(e.target===m){p?.pause();m.classList.remove("active")}});document.getElementById("playPauseBtn")?.addEventListener("click",()=>p?.paused?p?.play():p?.pause());document.getElementById("fullscreenBtn")?.addEventListener("click",()=>p?.requestFullscreen?.());document.getElementById("prevVideo")?.addEventListener("click",()=>this.play(this.index-1));document.getElementById("nextVideo")?.addEventListener("click",()=>this.play(this.index+1));p?.addEventListener("play",()=>{const b=document.getElementById("playPauseBtn");if(b)b.innerHTML='<i class="fas fa-pause"></i>'});p?.addEventListener("pause",()=>{const b=document.getElementById("playPauseBtn");if(b)b.innerHTML='<i class="fas fa-play"></i>'})}
 play(i){if(i<0||i>=this.filtered.length)return;const v=this.filtered[i],p=document.getElementById("videoPlayer"),m=document.getElementById("videoPlayerModal");if(!p||!m||!v?.videoUrl)return;this.index=i;p.src=v.videoUrl;p.poster=v.thumbnailUrl||"";m.classList.add("active");p.play().catch(()=>{});this.updateViews(v)}
 async updateViews(v){try{await updateDoc(doc(firestore,"videos",v.id),{views:increment(1)})}catch(e){console.error("Could not update views:",e)}}
 score(v){const l=+v.likes||0,c=+v.comments||0,s=+v.shares||0,w=+v.views||0;return ((l+c+s)*4)+(l*2)+w}
 date(v){if(!v)return 0;if(typeof v.toMillis==="function")return v.toMillis();if(v.seconds)return v.seconds*1000;const n=new Date(v).getTime();return Number.isFinite(n)?n:0}
 formatDate(v){const n=this.date(v);return n?new Intl.DateTimeFormat("en",{month:"short",day:"numeric",year:"numeric"}).format(new Date(n)):"Recently"}
 num(v){return new Intl.NumberFormat("en",{notation:"compact",maximumFractionDigits:1}).format(+v||0)}
 escape(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]))}
 attr(v){return this.escape(v)}
}
document.addEventListener("DOMContentLoaded",()=>{if(document.getElementById("videosContainer"))new VideosPage()});
export { VideosPage };
