(function(g){'use strict';if(g.HshsSkeleton)return;
var P=['home','gallery','photos','videos','about','trending','more','search','spotlight','settings','chat','admin','profile','notifications','saved','buzz','contact','polls','memories'];
function chrome(){return '<div class="hshs-skel-topbar"><span class="sk brand"></span><span class="actions"><span class="sk"></span><span class="sk"></span></span></div>'}
function bottom(){return '<div class="hshs-skel-bottom"><span class="item"><span class="sk ico"></span><span class="sk txt"></span></span><span class="item"><span class="sk ico"></span><span class="sk txt"></span></span><span class="item"><span class="sk ico"></span></span><span class="item"><span class="sk ico"></span><span class="sk txt"></span></span><span class="item"><span class="sk ico"></span><span class="sk txt"></span></span></div>'}
function lines(n){var s='';for(var i=0;i<n;i++)s+='<span class="sk sk-line '+(i===0?'lg':'')+'" style="width:'+([72,88,58,78][i%4])+'%"></span>';return s}
function account(kind){var title=kind==='search'?'Search':kind==='settings'?'Settings':kind==='notifications'?'Notifications':kind==='saved'?'Saved':'More';var body='';
if(kind==='search')body='<span class="sk sk-search"></span><div class="skel-tabs"><span class="sk sk-chip"></span><span class="sk sk-chip"></span><span class="sk sk-chip"></span></div><div class="skel-list">'+Array(6).fill('<div class="sk skel-search-result sk-row"><span class="sk sk-circle"></span><span style="display:grid;gap:8px;flex:1">'+lines(2)+'</span></div>').join('')+'</div>';
else if(kind==='more')body='<div class="sk skel-more-card sk-row"><span class="sk sk-circle"></span><span style="display:grid;gap:8px;flex:1">'+lines(2)+'</span></div><div class="skel-list">'+Array(9).fill('<div class="sk skel-menu sk-row"><span class="sk sk-circle" style="width:28px;height:28px;flex-basis:28px"></span><span style="flex:1">'+lines(1)+'</span></div>').join('')+'</div>';
else body='<div class="skel-tabs"><span class="sk sk-chip"></span><span class="sk sk-chip"></span><span class="sk sk-chip"></span></div><div class="skel-list">'+Array(6).fill('<div class="sk skel-list-card sk-row"><span class="sk sk-circle"></span><span style="display:grid;gap:8px;flex:1">'+lines(3)+'</span></div>').join('')+'</div>';
return '<main class="skel-account"><div class="skel-head"><span class="sk back"></span><span class="sk title"></span></div>'+body+'</main>'}
function make(page){var s='<div class="hshs-load-skel" data-skel-page="'+page+'" role="status" aria-label="Loading">';if(page!=='buzz'&&page!=='profile')s+=chrome();
if(page==='home')s+='<div class="hshs-skel-page"><span class="sk skel-home-hero"></span><div class="skel-home-stats"><span class="sk skel-stat"></span><span class="sk skel-stat"></span></div><div class="skel-home-trending"><span class="sk skel-home-trend"></span><span class="sk skel-home-trend"></span></div><div class="sk skel-event"></div><div class="sk skel-event"></div><div class="sk skel-event"></div></div>';
else if(page==='gallery'||page==='photos')s+='<div class="hshs-skel-page"><div class="skel-filter-row"><span class="sk sk-chip"></span><span class="sk sk-chip"></span><span class="sk sk-chip"></span><span class="sk sk-chip"></span></div><div class="skel-gallery-grid">'+Array(6).fill('<div class="sk skel-gallery-card"><div class="sk media"></div><div class="copy"><span class="sk sk-line"></span><span class="sk sk-line sm" style="width:62%;margin-top:7px"></span></div></div>').join('')+'</div></div>';
else if(page==='videos')s+='<div class="hshs-skel-page"><span class="sk skel-video-head"></span><div class="skel-video-grid">'+Array(6).fill('<div class="sk skel-video-card"><div class="sk skel-video-thumb"></div><div class="skel-video-meta"><span class="sk sk-line"></span><span class="sk sk-line sm" style="width:64%;margin-top:8px"></span></div></div>').join('')+'</div></div>';
else if(page==='buzz')s='<div class="hshs-load-skel skel-buzz" data-skel-page="buzz" role="status" aria-label="Loading"><span class="sk media"></span><span class="caption"><span class="sk sk-line lg"></span><span class="sk sk-line" style="width:82%"></span><span class="sk sk-line sm" style="width:58%"></span></span><span class="rail"><span class="sk sk-circle"></span><span class="sk action"></span><span class="sk action"></span><span class="sk action"></span></span></div>';
else if(page==='chat')s+='<div class="skel-chat-layout"><div class="skel-chat-list">'+Array(8).fill('<div class="sk skel-chat-row sk-row"><span class="sk sk-circle"></span><span style="display:grid;gap:8px;flex:1">'+lines(2)+'</span></div>').join('')+'</div><div class="sk skel-chat-thread"></div></div>';
else if(page==='profile')s='<div class="hshs-load-skel skel-profile" data-skel-page="profile" role="status" aria-label="Loading"><span class="sk skel-cover skel-profile-cover"></span><div class="skel-profile-head"><span class="sk skel-profile-avatar sk-circle"></span><span class="skel-profile-names">'+lines(3)+'</span></div><div class="skel-profile-stats">'+Array(4).fill('<span class="sk skel-profile-stat"></span>').join('')+'</div><span class="sk skel-profile-tabs"></span><div class="skel-profile-grid">'+Array(12).fill('<span class="sk sk-img"></span>').join('')+'</div></div>';
else if(page==='polls')s+='<div class="hshs-skel-page"><span class="sk skel-polls-hero"></span><span class="sk skel-section" style="height:58px"></span><section class="sk skel-section"><div class="skel-poll-grid">'+Array(4).fill('<span class="sk skel-poll"></span>').join('')+'</div></section><section class="sk skel-section" style="min-height:180px"></section><section class="sk skel-section"><div class="skel-poll-grid">'+Array(3).fill('<span class="sk skel-poll"></span>').join('')+'</div></section></div>';
else if(page==='memories')s+='<div class="hshs-skel-page"><span class="sk skel-memories-hero"></span><span class="sk skel-section" style="height:58px"></span><section class="sk skel-section" style="min-height:240px"></section><section class="sk skel-section"><div class="skel-memory-reel">'+Array(5).fill('<span class="sk skel-memory-card"></span>').join('')+'</div></section><section class="sk skel-section" style="min-height:220px"></section><section class="sk skel-section"><div class="skel-year-grid">'+Array(8).fill('<span class="sk skel-year"></span>').join('')+'</div></section></div>';
else if(page==='spotlight')s+='<div class="hshs-skel-page"><span class="sk skel-spot-hero"></span><div class="skel-spot-stats">'+Array(3).fill('<span class="sk" style="min-height:76px"></span>').join('')+'</div><span class="sk skel-spot-feature"></span><div class="skel-spot-grid">'+Array(6).fill('<span class="sk skel-spot-card"></span>').join('')+'</div><div class="skel-lower"><span class="sk skel-panel"></span><span class="sk skel-panel"></span></div></div>';
else if(page==='about')s+='<div class="hshs-skel-page"><span class="sk skel-about-block" style="min-height:170px"></span><span class="sk skel-about-block"></span><span class="sk skel-about-block"></span><div class="skel-feature-grid">'+Array(6).fill('<span class="sk skel-feature"></span>').join('')+'</div><span class="sk skel-about-block" style="min-height:160px"></span><span class="sk skel-about-block" style="min-height:140px"></span></div>';
else if(page==='contact')s+='<div class="hshs-skel-page"><span class="sk skel-about-block" style="min-height:150px"></span><div class="skel-contact-grid"><span class="sk skel-about-block"></span><span class="sk skel-form">'+Array(5).fill('<span class="sk skel-field" style="display:block;margin-bottom:10px"></span>').join('')+'<span class="sk skel-field" style="height:48px;display:block"></span></span></div><div class="skel-list">'+Array(4).fill('<span class="sk skel-list-card"></span>').join('')+'</div></div>';
else if(page==='trending')s+='<div class="hshs-skel-page"><span class="sk skel-about-block" style="min-height:160px"></span><div class="skel-filter-row"><span class="sk sk-chip"></span><span class="sk sk-chip"></span><span class="sk sk-chip"></span><span class="sk sk-chip"></span></div><div class="sk-grid-2">'+Array(2).fill('<span class="sk" style="min-height:183px"></span>').join('')+'</div><div class="sk-grid-2">'+Array(6).fill('<span class="sk" style="min-height:150px"></span>').join('')+'</div><div class="skel-list">'+Array(4).fill('<span class="sk skel-list-card"></span>').join('')+'</div></div>';
else if(page==='admin')s+='<div class="hshs-skel-page"><span class="sk skel-admin"></span><div class="skel-admin-grid">'+Array(4).fill('<span class="sk skel-admin-stat"></span>').join('')+'</div><span class="sk skel-admin" style="min-height:260px"></span></div>';
else if(page==='settings'||page==='notifications'||page==='saved'||page==='more'||page==='search')s+=account(page);
else s+='<div class="hshs-skel-page"><span class="sk skel-about-block"></span><div class="skel-list">'+Array(5).fill('<span class="sk skel-list-card"></span>').join('')+'</div></div>';
if(page!=='profile'&&page!=='buzz')s+=bottom();return s+'</div>'}
function get(page){return make(P.indexOf(page)!==-1?page:'home')}function insert(root,page){if(!root)return;var old=root.querySelector('.hshs-load-skel');if(old)old.remove();root.insertAdjacentHTML('afterbegin',get(page));}
g.HshsSkeleton={pages:P,get:get,insert:insert};})(typeof window!=='undefined'?window:this);