(function (g) {
  'use strict';
  g.HshsTemplates = g.HshsTemplates || {};
  g.HshsTemplates.spotlight = [
    '<main class="sp-page">',
    '<section class="sp-hero">',
    '<div class="sp-hero-copy">',
    '<span class="sp-kicker">Hawthorne Scribner · Campus hall</span>',
    '<h1>Student Spotlight</h1>',
    '<p>Achievements, teams, clubs, and classroom moments worth a closer look.</p>',
    '</div>',
    '<div class="sp-hero-mark" aria-hidden="true"><i class="fas fa-award"></i></div>',
    '</section>',
    '<section class="sp-stats" id="spStats" aria-label="Spotlight totals"></section>',
    '<section class="sp-feature" aria-labelledby="spFeatureTitle">',
    '<div class="sp-section-head"><span>This week</span><h2 id="spFeatureTitle">Featured</h2></div>',
    '<div id="featuredStudent" class="sp-feature-card">Loading spotlight…</div>',
    '</section>',
    '<section class="sp-board" aria-labelledby="spBoardTitle">',
    '<div class="sp-section-head"><span>Campus halls</span><h2 id="spBoardTitle">Browse by area</h2></div>',
    '<div class="sp-filters" id="spFilters" role="tablist"></div>',
    '<div id="spotlightGrid" class="sp-grid"></div>',
    '</section>',
    '<section class="sp-split">',
    '<div class="sp-panel">',
    '<div class="sp-section-head"><span>Ranked from real posts</span><h2>Hall of Fame</h2></div>',
    '<div id="hallOfFameList" class="sp-hall"></div>',
    '</div>',
    '<div class="sp-panel">',
    '<div class="sp-section-head"><span>What gets featured</span><h2>Categories</h2></div>',
    '<div id="spotlightCategories" class="sp-cats"></div>',
    '</div>',
    '</section>',
    '<section class="sp-nominate" id="spotlightCta">',
    '<div class="sp-section-head"><span>For staff review</span><h2>Nominate a student</h2></div>',
    '<p class="sp-note">Nominations stay on this device until a staff member features the moment in the gallery.</p>',
    '<form id="spNominateForm" class="sp-form">',
    '<label>Student name<input name="name" maxlength="48" required placeholder="First name and class"></label>',
    '<label>Class<input name="classTag" maxlength="24" placeholder="S2, S4 East…"></label>',
    '<label>Area<select name="category"><option>Academics</option><option>Sports</option><option>Arts</option><option>Leadership</option><option>Community</option><option>Events</option></select></label>',
    '<label>Achievement<textarea name="note" maxlength="180" required placeholder="What should the school notice?"></textarea></label>',
    '<button type="submit"><i class="fas fa-star"></i> Save nomination</button>',
    '<p id="spFormStatus" class="sp-status" role="status"></p>',
    '</form>',
    '<div id="spNominations" class="sp-noms"></div>',
    '</section>',
    '<div class="sp-sheet" id="studentModal" hidden>',
    '<button class="sp-sheet-back" id="modalOverlay" type="button" aria-label="Close"></button>',
    '<div class="sp-sheet-card" role="dialog" aria-modal="true" aria-labelledby="spSheetTitle">',
    '<button class="sp-sheet-close" id="closeModal" type="button" aria-label="Close"><i class="fas fa-times"></i></button>',
    '<div id="modalBody"></div>',
    '</div>',
    '</div>',
    '</main>'
  ].join('');
})(typeof window !== 'undefined' ? window : this);
