(function (global) {
  'use strict';
  var PAGE = 'buzz';
  if (global.__hshsBuzzPageModule) return;
  global.__hshsBuzzPageModule = true;
  var state = { mounted:false, items:[], all:[], feed:'discover', active:-1, muted:readMute(), liked:new Set(), saved:new Set(), follows:readFollows(), observer:null, chrome:false, tapTimer:null, holdTimer:null, holding:false };
  function readMute(){ try { return sessionStorage.getItem('hshsVibeMuted')==='1'; } catch(e){ return false; } }
  function writeMute(on){ state.muted=!!on; try{ sessionStorage.setItem('hshsVibeMuted', on?'1':'0'); }catch(e){} }
  function readFollows(){ try { return new Set(JSON.parse(localStorage.getItem('hshsVibeFollows')||'[]')); } catch(e){ return new Set(); } }
  function writeFollows(){ try { localStorage.setItem('hshsVibeFollows', JSON.stringify(Array.from(state.follows))); } catch(e){} }
  function isPage(){ var path=location.pathname.toLowerCase(); return /\/(buzz|clips|shorts|vibe)\.html$/.test(path) || path==='/buzz' || path==='/vibe' || path==='/clips'; }
  function base(){ return location.pathname.indexOf('/index/')!==-1 ? '../' : ''; }
  function esc(value){ return String(value==null?'':value).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];}); }
  function mediaUrl(item){ return item.video_url||item.videoUrl||item.url||item.media_url||item.mediaUrl||item.src||''; }
  function posterUrl(item){ return item.thumbnail||item.thumbnail_url||item.thumbnailUrl||item.cover||item.image_url||item.imageUrl||''; }
  function title(item){ return item.title||item.caption||item.description||'HSHS moment'; }
  function author(item){ return String(item.author||item.username||item.userName||item.creator||item.user||'HSHS Student'); }
  function avatar(item){ return item.avatar||item.profilePhoto||item.userPhoto||''; }
  function count(item,key){ return Number(item[key]??item[key+'Count']??0)||0; }
  function loadCss(){ [['css/hshs-wave.css','wave'],['css/buzz.css','buzz']].forEach(function(pair){ if(document.querySelector('link[data-hshs-css="'+pair[0]+'"]')) return; var link=document.createElement('link'); link.rel='stylesheet'; link.href=base()+pair[0]+'?v=260907vibe'; link.dataset.hshsCss=pair[0]; document.head.appendChild(link); }); }
  function toast(message){ var el=document.getElementById('buzzToast'); if(!el)return; el.textContent=message; el.classList.add('show'); clearTimeout(toast.timer); toast.timer=setTimeout(function(){el.classList.remove('show');},1700); }
  function visibleItems(){ if(state.feed!=='following') return state.all; return state.all.filter(function(item){ return state.follows.has(author(item).toLowerCase()); }); }
  function render(){ var feed=document.getElementById('buzzFeed'); if(!feed)return; state.items=visibleItems(); if(!state.items.length){ var emptyFollow=state.feed==='following'; feed.innerHTML='<div class="buzz-state buzz-empty"><i class="far fa-circle-play"></i><strong>'+(emptyFollow?'No followed creators yet':'No Vibe videos yet')+'</strong><small>'+(emptyFollow?'Tap + on an avatar in Discover to follow them here.':'Check back soon — new HSHS clips will land here.')+'</small></div>'; return; }
    feed.innerHTML=state.items.map(function(item,index){ var id=String(item.id||index); var src=mediaUrl(item), poster=posterUrl(item), who=author(item); var likes=count(item,'likes'), comments=count(item,'comments'); var cap=String(item.description&&item.description!==title(item)?item.description:title(item)); var followed=state.follows.has(who.toLowerCase()); var pic=avatar(item);
      return '<article class="buzz-card" data-buzz-id="'+esc(id)+'" data-index="'+index+'" data-author="'+esc(who)+'">'+ '<div class="buzz-media">'+(src?'<video playsinline webkit-playsinline loop preload="metadata" '+(poster?'poster="'+esc(poster)+'" ':'')+'src="'+esc(src)+'"></video>':'<div class="buzz-placeholder"><i class="fas fa-video-slash"></i></div>')+'</div>'+ '<div class="buzz-shade"></div><div class="buzz-vignette"></div>'+ '<div class="hshs-wave-slot"><div class="hshs-wave" aria-hidden="true"><i></i><i></i><i></i></div></div>'+ '<button class="buzz-retry" type="button" data-buzz-action="retry"><i class="fas fa-rotate-right"></i> Retry</button>'+ '<button class="buzz-sound" type="button" data-buzz-action="sound" aria-label="Toggle sound"><i class="fas '+(state.muted?'fa-volume-xmark':'fa-volume-high')+'"></i></button>'+ '<div class="buzz-play"><i class="fas fa-play"></i></div>'+ '<div class="buzz-rail"><div class="buzz-avatar">'+(pic?'<img src="'+esc(pic)+'" alt="">':'<span><i class="fas fa-user"></i></span>')+'<button class="buzz-follow'+(followed?' is-on':'')+'" type="button" data-buzz-action="follow" aria-label="Follow">+</button></div>'+ '<button class="buzz-action'+(state.liked.has(id)?' liked':'')+'" type="button" data-buzz-action="like"><i class="fas fa-heart"></i><span>'+likes+'</span></button>'+ '<button class="buzz-action" type="button" data-buzz-action="comments"><i class="fas fa-comment-dots"></i><span>'+comments+'</span></button>'+ '<button class="buzz-action" type="button" data-buzz-action="share"><i class="fas fa-share"></i><span>Share</span></button>'+ '<button class="buzz-action'+(state.saved.has(id)?' saved':'')+'" type="button" data-buzz-action="save"><i class="fas fa-bookmark"></i></button>'+ '<a class="buzz-crest" href="'+base()+'index/videos.html" aria-label="HSHS Studio">H</a></div>'+ '<div class="buzz-info"><div class="buzz-author">@'+esc(who.replace(/^@/,''))+'</div><div class="buzz-caption is-clamp" data-buzz-action="expand">'+esc(cap)+(cap.length>78?' <button class="buzz-more" type="button" data-buzz-action="expand">more</button>':'')+'</div><div class="buzz-audio"><i class="fas fa-compact-disc"></i> Original audio · HSHS Studio</div></div></article>'; }).join(''); bindVideos(); setupObserver(); }
  function bindVideos(){ document.querySelectorAll('.buzz-card video').forEach(function(video){ video.muted=state.muted; video.loop=true; video.addEventListener('playing',function(){ var card=video.closest('.buzz-card'); card.classList.add('is-playing','is-loaded'); card.classList.remove('is-paused','is-waiting','is-error','is-held'); }); video.addEventListener('waiting',function(){ video.closest('.buzz-card').classList.add('is-waiting'); }); video.addEventListener('canplay',function(){ video.closest('.buzz-card').classList.add('is-loaded'); video.closest('.buzz-card').classList.remove('is-waiting'); }); video.addEventListener('pause',function(){ video.closest('.buzz-card').classList.remove('is-playing'); }); video.addEventListener('error',function(){ video.closest('.buzz-card').classList.add('is-error'); }); video.addEventListener('timeupdate',updateProgress); }); }
  function setupObserver(){ if(state.observer) state.observer.disconnect(); var feed=document.getElementById('buzzFeed'); if(!feed)return; state.observer=new IntersectionObserver(function(entries){ entries.forEach(function(entry){ var card=entry.target, video=card.querySelector('video'); if(entry.isIntersecting && entry.intersectionRatio>=0.65){ state.active=Number(card.dataset.index); card.classList.remove('is-away'); document.querySelectorAll('.buzz-card').forEach(function(other){ if(other!==card){ other.classList.add('is-away'); var v=other.querySelector('video'); if(v) v.pause(); } }); if(video){ video.muted=state.muted; var p=video.play(); if(p&&p.catch) p.catch(function(){ card.classList.add('is-paused'); }); } } else if(video){ video.pause(); card.classList.add('is-away'); } }); }, { root:feed, threshold:[0.3,0.65,1] }); document.querySelectorAll('.buzz-card').forEach(function(card){ state.observer.observe(card); }); }
  function updateProgress(){ var card=document.querySelector('.buzz-card[data-index="'+state.active+'"]'); var video=card&&card.querySelector('video'); var bar=document.getElementById('buzzProgress'); if(!bar)return; bar.style.width=(video&&video.duration?Math.min(100,(video.currentTime/video.duration)*100):0)+'%'; }
  function activeCard(){ return document.querySelector('.buzz-card[data-index="'+state.active+'"]'); }
  function activeItem(){ return state.items[state.active]||null; }
  function setChrome(on){ state.chrome=!!on; document.body.classList.toggle('vibe-chrome', state.chrome); }
  async function loadVideos(){ var videos=[]; try{ if(global.db && typeof global.db.getVideos==='function') videos=await global.db.getVideos(24,0); }catch(error){ console.error('[HSHS Vibe] video query failed', error); } state.all=(videos||[]).filter(function(item){ return !!mediaUrl(item); }); render(); }
  async function likeActive(button, burstAt){ var item=activeItem(); if(!item)return; var id=String(item.id); if(!state.liked.has(id)){ state.liked.add(id); if(button){ button.classList.add('liked'); var span=button.querySelector('span'); if(span) span.textContent=count(item,'likes')+1; } if(global.db&&typeof global.db.addLike==='function') await global.db.addLike(item.id,'video'); } if(burstAt) burstHeart(burstAt.x, burstAt.y); }
  function burstHeart(x,y){ var card=activeCard(); if(!card)return; var rec=card.getBoundingClientRect(); var el=document.createElement('i'); el.className='fas fa-heart buzz-heart-burst'; el.style.left=(x-rec.left)+'px'; el.style.top=(y-rec.top)+'px'; card.appendChild(el); setTimeout(function(){ el.remove(); },720); }
  function saveActive(button){ var item=activeItem(); if(!item)return; var id=String(item.id); if(state.saved.has(id)) state.saved.delete(id); else state.saved.add(id); if(global.HshsStore&&typeof global.HshsStore.toggleSave==='function'){ try{ global.HshsStore.toggleSave(item.id); }catch(e){} } button.classList.toggle('saved', state.saved.has(id)); toast(state.saved.has(id)?'Saved':'Removed from saves'); }
  async function shareActive(){ var item=activeItem(); if(!item)return; var url=location.origin+'/index/buzz.html#'+encodeURIComponent(item.id); try{ if(navigator.share) await navigator.share({ title:title(item), text:'HSHS Vibe · '+title(item), url:url }); else { await navigator.clipboard.writeText(url); toast('Vibe link copied'); } }catch(e){} }
  async function comments(){ var item=activeItem(), box=document.getElementById('buzzComments'), list=document.getElementById('buzzCommentList'); if(!item||!box||!list)return; box.hidden=false; box.classList.add('is-open'); document.body.classList.add('vibe-chrome'); var video=activeCard()&&activeCard().querySelector('video'); if(video) video.pause(); list.innerHTML='<div class="buzz-state" style="height:auto;padding:30px"><div class="hshs-wave"><i></i><i></i><i></i></div><small>Loading comments…</small></div>'; var rows=[]; try{ if(global.db&&typeof global.db.getComments==='function') rows=await global.db.getComments(item.id); }catch(e){} paintComments(rows); }
  function paintComments(rows){ var list=document.getElementById('buzzCommentList'); if(!list)return; if(!rows||!rows.length){ list.innerHTML='<div class="buzz-state" style="height:auto;padding:28px"><small>No comments yet. Be first.</small></div>'; return; } list.innerHTML=rows.map(function(c){ var name=c.author||c.username||'Student'; return '<div class="buzz-comment"><div class="ava">'+esc(String(name).charAt(0).toUpperCase())+'</div><div><strong>'+esc(name)+'</strong><p>'+esc(c.text||c.comment||'')+'</p></div><span class="lc"></span></div>'; }).join(''); }
  function closeComments(){ var box=document.getElementById('buzzComments'); if(box){ box.hidden=true; box.classList.remove('is-open'); } var video=activeCard()&&activeCard().querySelector('video'); if(video){ video.muted=state.muted; video.play().catch(function(){}); } }
  async function postComment(text){ var item=activeItem(); if(!item||!text)return; try{ if(global.db&&typeof global.db.addComment==='function') await global.db.addComment(item.id,text); }catch(e){} var list=document.getElementById('buzzCommentList'); if(list&&list.querySelector('.buzz-state')) list.innerHTML=''; if(list){ var wrap=document.createElement('div'); wrap.innerHTML='<div class="buzz-comment"><div class="ava">Y</div><div><strong>You</strong><p>'+esc(text)+'</p></div><span class="lc"></span></div>'; list.prepend(wrap.firstChild); } }
  function bind(){ if(global.__hshsBuzzEvents)return; global.__hshsBuzzEvents=true;
    document.addEventListener('click',function(e){ if(!isPage())return; var action=e.target.closest('[data-buzz-action]'); if(action){ var name=action.dataset.buzzAction; if(name==='sound'){ writeMute(!state.muted); document.querySelectorAll('.buzz-card video').forEach(function(v){ v.muted=state.muted; }); document.querySelectorAll('.buzz-sound').forEach(function(btn){ btn.innerHTML='<i class="fas '+(state.muted?'fa-volume-xmark':'fa-volume-high')+'"></i>'; }); return; } if(name==='like'){ likeActive(action); return; } if(name==='save'){ saveActive(action); return; } if(name==='share'){ shareActive(); return; } if(name==='comments'){ comments(); return; } if(name==='close-comments'){ closeComments(); return; } if(name==='follow'){ var card=action.closest('.buzz-card'); var who=(card&&card.dataset.author||'').toLowerCase(); if(!who)return; if(state.follows.has(who)) state.follows.delete(who); else state.follows.add(who); writeFollows(); action.classList.toggle('is-on', state.follows.has(who)); action.textContent=state.follows.has(who)?'\u2713':'+'; toast(state.follows.has(who)?'Following':'Unfollowed'); return; } if(name==='feed'){ state.feed=action.dataset.feed||'discover'; document.querySelectorAll('.vibe-switch').forEach(function(tab){ tab.classList.toggle('is-on', tab===action); tab.setAttribute('aria-selected', tab===action?'true':'false'); }); render(); return; } if(name==='expand'){ var cap=e.target.closest('.buzz-caption'); if(cap) cap.classList.remove('is-clamp'); return; } if(name==='retry'){ var video=action.closest('.buzz-card').querySelector('video'); if(video){ action.closest('.buzz-card').classList.remove('is-error'); video.load(); video.play().catch(function(){}); } return; } } if(e.target.closest('.buzz-comments')||e.target.closest('.buzz-rail')||e.target.closest('.buzz-topbar')) return; var card=e.target.closest('.buzz-card'); if(!card)return; clearTimeout(state.tapTimer); state.tapTimer=setTimeout(function(){ setChrome(!state.chrome); },240); });
    document.addEventListener('dblclick',function(e){ if(!isPage())return; var card=e.target.closest('.buzz-card'); if(!card)return; clearTimeout(state.tapTimer); likeActive(card.querySelector('[data-buzz-action="like"]'), {x:e.clientX,y:e.clientY}); });
    document.addEventListener('pointerdown',function(e){ if(!isPage()||e.target.closest('button,a,input,.buzz-comments')) return; var card=e.target.closest('.buzz-card'); if(!card)return; state.holdTimer=setTimeout(function(){ state.holding=true; card.classList.add('is-held','is-paused'); var video=card.querySelector('video'); if(video) video.pause(); },280); });
    function endHold(){ clearTimeout(state.holdTimer); if(!state.holding)return; state.holding=false; var card=activeCard(); if(!card)return; card.classList.remove('is-held'); var video=card.querySelector('video'); if(video){ video.muted=state.muted; video.play().catch(function(){}); } }
    document.addEventListener('pointerup', endHold); document.addEventListener('pointercancel', endHold);
    document.addEventListener('keydown',function(e){ if(!isPage())return; var feed=document.getElementById('buzzFeed'); if(!feed)return; if(e.key==='ArrowDown'){ e.preventDefault(); feed.scrollBy({top:feed.clientHeight,behavior:'smooth'}); } if(e.key==='ArrowUp'){ e.preventDefault(); feed.scrollBy({top:-feed.clientHeight,behavior:'smooth'}); } if(e.key==='Escape') closeComments(); });
    document.addEventListener('submit',function(e){ if(e.target.id!=='buzzCommentForm')return; e.preventDefault(); var input=document.getElementById('buzzCommentInput'); var text=input&&input.value.trim(); if(!text)return; postComment(text); input.value=''; });
  }
  async function mount(){ if(!isPage()||state.mounted||!global.HshsRender)return; var root=document.getElementById('hshs-page'); if(!root)return; loadCss(); var tpl=global.HshsTemplates&&global.HshsTemplates.buzz; if(!tpl){ console.error('[HSHS Vibe] template missing'); return; } global.HshsRender.mountHTML?global.HshsRender.mountHTML(root,tpl):root.innerHTML=tpl; document.documentElement.dataset.hshsPage=PAGE; document.body.classList.add('vibe-watching'); state.mounted=true; bind(); await loadVideos(); }
  function boot(){ var go=function(){ if(!isPage()){ document.body.classList.remove('vibe-watching','vibe-chrome'); return; } if(!global.HshsRender){ setTimeout(go,40); return; } mount(); }; if(global.HshsApp&&typeof global.HshsApp.whenReady==='function') global.HshsApp.whenReady(go); else if(document.readyState==='loading') document.addEventListener('DOMContentLoaded',go,{once:true}); else go(); }
  if(document.readyState==='loading') document.addEventListener('DOMContentLoaded',boot,{once:true}); else boot();
  global.HshsBuzz={ mount:mount, refresh:loadVideos };
})(typeof window!=='undefined'?window:this);
