(function (global) {
  'use strict';
  if (global.__hshsGalleryModernModule) return;
  global.__hshsGalleryModernModule = true;
  var PAGE = 'gallery', PAGE_SIZE = 9;
  var state = { type:'all', category:'all', query:'', all:[], items:[], offset:0, loading:false, done:false, observer:null, view:-1 };
  function isPage(){ var p=(location.pathname.split('/').pop()||'').toLowerCase(); return p==='gallery.html'||p==='gallery'; }
  function base(){ return location.pathname.indexOf('/index/')!==-1?'../':''; }
  function esc(v){ return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];}); }
  function count(v){ v=Number(v)||0; return v>999?(v/1000).toFixed(v>9999?0:1).replace('.0','')+'k':String(v); }
  function date(v){ if(global.Utils&&Utils.formatDate) return Utils.formatDate(v); var d=v&&v.toDate?v.toDate():new Date(v); return isNaN(d)?'Recently':d.toLocaleDateString(undefined,{month:'short',day:'numeric'}); }
  function kindOf(p){ var t=String(p.type||p.media_type||'').toLowerCase(); if(t.indexOf('video')!==-1||p.videoUrl||p.video_url) return 'video'; return 'photo'; }
  function mediaUrl(p){ return p.imageUrl||p.image_url||p.thumbnailUrl||p.thumbnail_url||p.image||p.cover||p.mediaUrl||p.media_url||''; }
  function videoUrl(p){ return p.videoUrl||p.video_url||(kindOf(p)==='video'?(p.url||p.src||''):''); }
  function loadCss(){ ['css/hshs-wave.css','css/gallery.css'].forEach(function(href){ if(document.querySelector('link[data-hshs-gallery-css="'+href+'"]')) return; var l=document.createElement('link'); l.rel='stylesheet'; l.href=base()+href+'?v=260907g2'; l.dataset.hshsGalleryCss=href; document.head.appendChild(l); }); }
  function normalize(row, fallbackType){ if(!row) return null; var item=Object.assign({},row); item.type=(fallbackType==='video'||kindOf(item)==='video')?'video':'photo'; item.title=item.title||item.caption||'HSHS moment'; item.author=item.author||item.username||item.userName||'HSHS World'; item.category=String(item.category||item.tag||'campus').toLowerCase(); item.likes=Number(item.likes||item.likesCount||0); item.comments=Number(item.comments||item.commentsCount||0); item.saves=Number(item.saves||0); item.shares=Number(item.shares||0); item.createdAt=item.createdAt||item.date||Date.now(); item._media=mediaUrl(item); item._video=videoUrl(item); if(!item._media&&!item._video) return null; return item; }
  function visible(){ var q=state.query; return state.all.filter(function(p){ if(state.type!=='all'&&p.type!==state.type) return false; if(state.category!=='all'&&p.category!==state.category) return false; if(q&&(p.title+' '+(p.description||'')+' '+p.author+' '+p.category).toLowerCase().indexOf(q)===-1) return false; return true; }); }
  function renderCard(p,i){ var isVideo=p.type==='video'; var media=isVideo&&p._video?'<video class="gallery-media" src="'+esc(p._video)+'" poster="'+esc(p._media)+'" muted playsinline preload="metadata"></video>':'<img class="gallery-media" src="'+esc(p._media)+'" alt="'+esc(p.title)+'" loading="'+(i<3?'eager':'lazy')+'">'; return '<article class="gallery-card" data-id="'+esc(p.id)+'" data-index="'+i+'"><div class="gallery-media-wrap" data-open="'+i+'">'+media+'<div class="gallery-vignette"></div><span class="gallery-type"><i class="fas '+(isVideo?'fa-play':'fa-image')+'"></i> '+(isVideo?'Video':'Photo')+'</span><span class="gallery-category">'+esc(p.category)+'</span><div class="gallery-card-copy"><div class="gallery-author"><span>'+esc(p.author)+'</span><time>'+esc(date(p.createdAt))+'</time></div><h2>'+esc(p.title)+'</h2>'+(p.description?'<p>'+esc(p.description)+'</p>':'')+'</div></div><div class="gallery-actions"><button type="button" data-action="like"><i class="far fa-heart"></i><span>'+count(p.likes)+'</span></button><button type="button" data-action="comment"><i class="far fa-comment"></i><span>'+count(p.comments)+'</span></button><button type="button" data-action="save"><i class="far fa-bookmark"></i></button><button type="button" data-action="share"><i class="fas fa-share"></i></button></div></article>'; }
  function paint(){ var feed=document.getElementById('galleryFeed'), empty=document.getElementById('galleryEmpty'), label=document.getElementById('galleryResultCount'); if(!feed)return; var list=visible(); state.items=list.slice(0,state.offset+PAGE_SIZE); state.done=state.items.length>=list.length; feed.innerHTML=state.items.map(renderCard).join(''); if(label) label.textContent=list.length?list.length+' moment'+(list.length===1?'':'s'):'No moments found'; if(empty) empty.hidden=list.length!==0; if(!list.length) feed.innerHTML=''; }
  async function loadAll(){ state.loading=true; setLoading(true); var posts=[],photos=[],videos=[],storePosts=[]; try{ if(global.db&&db.getPosts) posts=await db.getPosts(48,0);}catch(e){} try{ if(global.db&&db.getPhotos) photos=await db.getPhotos(48,0);}catch(e){} try{ if(global.db&&db.getVideos) videos=await db.getVideos(48,0);}catch(e){} try{ if(global.HshsStore&&typeof HshsStore.listPosts==='function') storePosts=HshsStore.listPosts();}catch(e){} var merged=[].concat((posts||[]).map(function(p){return normalize(p,p.type);})).concat((photos||[]).map(function(p){return normalize(p,'photo');})).concat((videos||[]).map(function(p){return normalize(p,'video');})).concat((storePosts||[]).map(function(p){return normalize(p,p.type);})).filter(Boolean); var seen={}; state.all=merged.filter(function(p){ var key=String(p.id||p._media||p.title); if(seen[key]) return false; seen[key]=1; return true; }).sort(function(a,b){ return new Date(b.createdAt)-new Date(a.createdAt); }); state.offset=0; state.loading=false; setLoading(false); paint(); }
  function setLoading(show){ var el=document.getElementById('galleryLoader'); if(el) el.hidden=!show; }
  function itemById(id){ for(var i=0;i<state.items.length;i++) if(String(state.items[i].id)===String(id)) return state.items[i]; return null; }
  async function onAction(action,id,btn){ var item=itemById(id); if(!item) return; if(action==='like'){ item.likes=(item.likes||0)+1; if(btn){ btn.classList.add('is-on'); var s=btn.querySelector('span'); if(s) s.textContent=count(item.likes);} try{ if(global.db&&db.addLike) await db.addLike(item.id,item.type);}catch(e){} return;} if(action==='save'){ btn&&btn.classList.toggle('is-on'); try{ if(global.HshsStore&&HshsStore.toggleSave) HshsStore.toggleSave(item.id);}catch(e){} return;} if(action==='share'){ var url=location.origin+'/index/gallery.html#'+encodeURIComponent(item.id); try{ if(navigator.share) await navigator.share({title:item.title,url:url}); else await navigator.clipboard.writeText(url);}catch(e){} return;} if(action==='comment') openViewer(state.items.indexOf(item)); }
  function openViewer(index){ var item=state.items[index], box=document.getElementById('galleryViewer'), stage=document.getElementById('galleryViewerStage'); if(!item||!box||!stage) return; state.view=index; box.hidden=false; document.body.style.overflow='hidden'; stage.innerHTML=item.type==='video'&&item._video?'<video src="'+esc(item._video)+'" poster="'+esc(item._media)+'" controls autoplay playsinline></video>':'<img src="'+esc(item._media)+'" alt="'+esc(item.title)+'">'; document.getElementById('gvTitle').textContent=item.title; document.getElementById('gvBy').textContent='@'+item.author+' · '+date(item.createdAt); }
  function closeViewer(){ var box=document.getElementById('galleryViewer'); if(box) box.hidden=true; document.body.style.overflow=''; var stage=document.getElementById('galleryViewerStage'); if(stage) stage.innerHTML=''; state.view=-1; }
  function bind(){ var root=document.getElementById('hshs-page'); if(!root||root.dataset.galleryBound) return; root.dataset.galleryBound='1';
    document.getElementById('categoryFilter')&&document.getElementById('categoryFilter').addEventListener('click',function(e){ var b=e.target.closest('.category-btn'); if(!b)return; document.querySelectorAll('.category-btn').forEach(function(x){x.classList.toggle('active',x===b);}); state.category=b.dataset.category; state.offset=0; paint(); });
    document.getElementById('galleryTypes')&&document.getElementById('galleryTypes').addEventListener('click',function(e){ var b=e.target.closest('[data-type]'); if(!b)return; document.querySelectorAll('#galleryTypes .gallery-chip').forEach(function(x){x.classList.toggle('is-on',x===b);}); state.type=b.dataset.type; state.offset=0; paint(); });
    var search=document.getElementById('gallerySearch'); if(search) search.addEventListener('input',function(){ state.query=search.value.trim().toLowerCase(); state.offset=0; paint(); });
    var share=document.getElementById('galleryShareBtn'); if(share) share.addEventListener('click',function(){ if(global.__hshsOpenUpload) global.__hshsOpenUpload(); else location.href=base()+'index/photos.html'; });
    root.addEventListener('click',function(e){ var open=e.target.closest('[data-open]'); if(open){ openViewer(Number(open.dataset.open)); return;} var act=e.target.closest('[data-action]'); if(act){ var card=act.closest('.gallery-card'); onAction(act.dataset.action, card&&card.dataset.id, act); return;} var gv=e.target.closest('[data-gv],[data-gv-act]'); if(!gv){ if(e.target.id==='galleryViewer') closeViewer(); return;} var cmd=gv.dataset.gv||gv.dataset.gvAct; if(cmd==='close') closeViewer(); if(cmd==='prev'&&state.view>0) openViewer(state.view-1); if(cmd==='next'&&state.view<state.items.length-1) openViewer(state.view+1); if(cmd==='like'||cmd==='save'||cmd==='share'){ var item=state.items[state.view]; if(item) onAction(cmd,item.id,gv); } });
    document.addEventListener('keydown',function(e){ if(!isPage())return; if(e.key==='Escape') closeViewer(); if(state.view<0)return; if(e.key==='ArrowLeft'&&state.view>0) openViewer(state.view-1); if(e.key==='ArrowRight'&&state.view<state.items.length-1) openViewer(state.view+1); });
    var sentinel=document.getElementById('gallerySentinel'); if(sentinel&&'IntersectionObserver'in global){ state.observer=new IntersectionObserver(function(es){ if(!es[0].isIntersecting||state.done||state.loading) return; state.offset+=PAGE_SIZE; paint(); },{rootMargin:'600px 0px'}); state.observer.observe(sentinel); }
  }
  function mount(){ if(!isPage()||!global.HshsRender) return; document.documentElement.dataset.hshsPage=PAGE; var root=document.getElementById('hshs-page'); if(!root){ root=document.createElement('div'); root.id='hshs-page'; document.body.appendChild(root);} var tpl=global.HshsTemplates&&HshsTemplates[PAGE]; if(tpl)(global.HshsRender.mountHTML?global.HshsRender.mountHTML(root,tpl):root.innerHTML=tpl); loadCss(); bind(); loadAll(); }
  function boot(){ var go=function(){ if(isPage()) mount(); }; if(global.HshsApp&&typeof HshsApp.whenReady==='function') HshsApp.whenReady(go); else if(document.readyState==='loading') document.addEventListener('DOMContentLoaded',go,{once:true}); else go(); }
  global.HshsGallery={ mount:mount, refresh:function(){ mount(); } };
  if(document.readyState==='loading') document.addEventListener('DOMContentLoaded',boot,{once:true}); else boot();
  document.addEventListener('hshs:page',function(){ if(isPage()) setTimeout(mount,0); });
})(typeof window!=='undefined'?window:this);
