(function(global){'use strict';var PAGE='polls';if(global['__hshs'+PAGE+'PageModule'])return;global['__hshs'+PAGE+'PageModule']=true;
var LOCAL_KEY='hshs_polls_local';
function isPage(){
  var path=(location.pathname||'').toLowerCase();
  var file=(path.split('/').pop()||'');
  if(file==='polls.html'||file==='polls')return true;
  if(document.documentElement.getAttribute('data-hshs-page')==='polls')return true;
  return !!document.querySelector('.hshs-polls-page,#activePollsList');
}
function base(){return location.pathname.indexOf('/index/')!==-1?'../':''}
function loadCss(href){if(document.querySelector('link[data-hshs-css="'+href+'"]'))return;var l=document.createElement('link');l.rel='stylesheet';l.href=base()+href+'?v=261002pollfix';l.setAttribute('data-hshs-css',href);document.head.appendChild(l)}
function voteKey(id){return'hshs_poll_vote_'+String(id||'unknown')}
function readLocal(){try{var raw=localStorage.getItem(LOCAL_KEY);var list=raw?JSON.parse(raw):[];return Array.isArray(list)?list:[]}catch(e){return[]}}
function writeLocal(list){try{localStorage.setItem(LOCAL_KEY,JSON.stringify(list))}catch(e){}}
function renderPoll(p){var options=Array.isArray(p.options)?p.options:[],total=options.reduce(function(n,o){return n+(Number(o.votes)||0)},0),selected=null;try{selected=localStorage.getItem(voteKey(p.id))}catch(e){}var card=document.createElement('article');card.className='poll-card'+(selected!==null?' is-voted':'');var top=document.createElement('div');top.className='poll-card-top';top.innerHTML='<span class="poll-badge"><i class="fas fa-circle"></i> '+(p.closed?'CLOSED':'LIVE')+'</span><span class="poll-badge">'+total+' vote'+(total===1?'':'s')+'</span>';card.appendChild(top);var title=document.createElement('h3');title.textContent=p.question||p.title||'School Poll';card.appendChild(title);options.forEach(function(o,i){var votes=Number(o.votes)||0,pct=total?Math.round(votes*100/total):0,b=document.createElement('button');b.type='button';b.className='poll-option'+(selected===String(i)?' is-selected':'');b.dataset.pollId=p.id||'';b.dataset.optionIndex=String(i);var bar=document.createElement('i');bar.style.width=pct+'%';var s=document.createElement('span');s.textContent=o.text||o.label||('Option '+(i+1));var v=document.createElement('b');v.textContent=pct+'%';b.append(bar,s,v);card.appendChild(b)});var foot=document.createElement('div');foot.className='poll-card-foot';var note=document.createElement('span');note.className=selected!==null?'poll-voted-note':'';note.innerHTML=selected!==null?'<i class="fas fa-circle-check"></i> Your choice is saved on this device.':'Tap an option to choose';var source=document.createElement('strong');source.textContent=p.closed?'Final results':'Live results';foot.append(note,source);card.appendChild(foot);return card}
function seed(){return[{id:'hp1',question:'Which house is leading spirit this term?',options:[{text:'Eagle',votes:42},{text:'Lion',votes:38},{text:'Falcon',votes:21}],closed:false},{id:'hp2',question:'Best Sports Day event?',options:[{text:'Track',votes:55},{text:'Football',votes:40},{text:'Tug of war',votes:18}],closed:false},{id:'hp3',question:'Favourite assembly song?',options:[{text:'School anthem',votes:70},{text:'Morning hymn',votes:22}],closed:true}];}
async function getPolls(){var remote=[];try{if(global.HshsStore&&typeof global.HshsStore.listPolls==='function')remote=await global.HshsStore.listPolls();else if(global.db&&typeof global.db.getPolls==='function')remote=await global.db.getPolls()}catch(e){console.error('[HSHS] Polls load failed',e)}remote=Array.isArray(remote)?remote.filter(Boolean):[];var local=readLocal();var seen={};return remote.concat(local).filter(function(p){var id=String(p&&p.id||'');if(!id||seen[id])return false;seen[id]=true;return true})}
function renderSnapshot(active,closed){var el=document.getElementById('pollSnapshot');if(!el)return;var votes=active.reduce(function(n,p){return n+(Array.isArray(p.options)?p.options.reduce(function(a,o){return a+(Number(o.votes)||0)},0):0)},0);el.innerHTML='<div class="poll-snapshot-card"><strong>'+active.length+'</strong><span>Live polls</span></div><div class="poll-snapshot-card"><strong>'+votes+'</strong><span>Votes represented</span></div><div class="poll-snapshot-card"><strong>'+closed.length+'</strong><span>Past polls</span></div>'}
function wireTabs(){var tabs=document.querySelectorAll('.polls-tabs a');tabs.forEach(function(a){a.addEventListener('click',function(){tabs.forEach(function(x){x.classList.remove('is-active')});a.classList.add('is-active')})})}
function wireVotes(){document.querySelectorAll('.poll-option').forEach(function(b){if(b.dataset.wired==='1')return;b.dataset.wired='1';b.addEventListener('click',function(){var id=b.dataset.pollId,idx=b.dataset.optionIndex;if(!id)return;try{localStorage.setItem(voteKey(id),String(idx))}catch(e){}var card=b.closest('.poll-card');if(card){card.classList.add('is-voted');card.querySelectorAll('.poll-option').forEach(function(x){x.classList.toggle('is-selected',x===b)});var note=card.querySelector('.poll-card-foot span');if(note){note.className='poll-voted-note';note.innerHTML='<i class="fas fa-circle-check"></i> Your choice is saved on this device.'}}})})}
function closeComposer(){var box=document.getElementById('pollComposer');if(box)box.remove();document.body.classList.remove('poll-composer-open')}
function openComposer(){if(document.getElementById('pollComposer'))return;var wrap=document.createElement('div');wrap.id='pollComposer';wrap.className='poll-composer';wrap.innerHTML='<form class="poll-composer-card" id="pollComposerForm"><p class="polls-kicker">NEW POLL</p><h3>Ask the school</h3><label>Question<input name="question" maxlength="120" required placeholder="What should HSHS vote on?"></label><label>Option 1<input name="o1" maxlength="40" required placeholder="First choice"></label><label>Option 2<input name="o2" maxlength="40" required placeholder="Second choice"></label><label>Option 3 <span>(optional)</span><input name="o3" maxlength="40" placeholder="Another choice"></label><div class="poll-composer-actions"><button type="button" id="pollComposerCancel">Cancel</button><button type="submit">Post poll</button></div></form>';document.body.appendChild(wrap);document.body.classList.add('poll-composer-open');wrap.addEventListener('click',function(e){if(e.target===wrap)closeComposer()});wrap.querySelector('#pollComposerCancel').addEventListener('click',closeComposer);wrap.querySelector('#pollComposerForm').addEventListener('submit',function(e){e.preventDefault();var data=new FormData(e.target);var question=String(data.get('question')||'').trim();var options=['o1','o2','o3'].map(function(k){return String(data.get(k)||'').trim()}).filter(Boolean).map(function(text){return{text:text,votes:0}});if(question.length<4||options.length<2)return;var list=readLocal();list.unshift({id:'local-'+Date.now(),question:question,options:options,closed:false});writeLocal(list);closeComposer();load()});var first=wrap.querySelector('input');if(first)first.focus()}
function wireCreate(){['createPollBtn','pollCtaButton'].forEach(function(id){var btn=document.getElementById(id);if(!btn||btn.dataset.wired==='1')return;btn.dataset.wired='1';btn.addEventListener('click',openComposer)})}
function mount(){if(!isPage())return;loadCss('css/polls.css');loadCss('css/hshs-hub.css');if(global.HshsShell)try{global.HshsShell.ensureShell()}catch(e){}var root=document.getElementById('hshs-page');if(!root){root=document.createElement('div');root.id='hshs-page';document.body.appendChild(root)}document.documentElement.setAttribute('data-hshs-page',PAGE);var tpl=global.HshsTemplates&&global.HshsTemplates[PAGE];if(tpl&&!document.getElementById('activePollsList')){if(global.HshsRender&&global.HshsRender.mountHTML)global.HshsRender.mountHTML(root,tpl);else root.innerHTML=tpl}load().catch(function(e){console.error(e)})}
async function load(){var active=document.getElementById('activePollsList'),closed=document.getElementById('closedPollsList');if(!active||!closed)return;var polls=await getPolls();if(!polls.length)polls=seed();var activePolls=polls.filter(function(p){return p.closed!==true&&p.status!=='closed'}),closedPolls=polls.filter(function(p){return p.closed===true||p.status==='closed'});active.innerHTML='';closed.innerHTML='';if(!activePolls.length)active.innerHTML='<div class="poll-empty">No active polls right now. Start one for the school.</div>';else activePolls.forEach(function(p){active.appendChild(renderPoll(p))});if(!closedPolls.length)closed.innerHTML='<div class="poll-empty">No past polls yet.</div>';else closedPolls.forEach(function(p){closed.appendChild(renderPoll(p))});var count=document.getElementById('pollCount');if(count)count.textContent=activePolls.length+' live poll'+(activePolls.length===1?'':'s');renderSnapshot(activePolls,closedPolls);wireVotes();wireTabs();wireCreate()}
function boot(){var go=function(){if(isPage())mount()};if(global.HshsApp&&global.HshsApp.whenReady)global.HshsApp.whenReady(go);else document.addEventListener('hshs:foundation-ready',go,{once:true});document.addEventListener('hshs:page',function(e){if(e&&e.detail&&e.detail.page===PAGE)mount()});go();setTimeout(go,400);setTimeout(function(){if(document.querySelector('.poll-loading'))go()},1200)}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot()})(typeof window!=='undefined'?window:this);
