(function (g) {
  'use strict';
  if (g.__hshsProfilePageModule) return;
  g.__hshsProfilePageModule = true;
  var PAGE = 'profile';
  var tab = 'grid';
  function isPage(){ try{ if(g.HshsRegistry&&HshsRegistry.activeRoute) return HshsRegistry.activeRoute().name===PAGE; }catch(e){} return (location.pathname.split('/').pop()||'').toLowerCase()==='profile.html'; }
  function base(){ return location.pathname.indexOf('/index/')!==-1?'../':''; }
  function store(){ return g.HshsStore||null; }
  function esc(v){ return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];}); }
  function abbr(n){ n=Number(n)||0; if(n>=1000000) return (n/1000000).toFixed(1).replace('.0','')+'M'; if(n>=1000) return (n/1000).toFixed(1).replace('.0','')+'K'; return String(n); }
  function mediaOf(p){ return p.imageUrl||p.image_url||p.thumbnailUrl||p.thumbnail||p.image||p.cover||''; }
  function videoOf(p){ return p.videoUrl||p.video_url||''; }
  function isVideo(p){ return String(p.type||p.media_type||'').toLowerCase().indexOf('video')!==-1||!!videoOf(p); }
  function loadCss(){ if(document.querySelector('link[data-hshs-profile-css]')) return; var l=document.createElement('link'); l.rel='stylesheet'; l.href=base()+'css/hshs-profile.css?v=260907pf3'; l.setAttribute('data-hshs-profile-css','1'); document.head.appendChild(l); }
  function me(){ try{ return store()&&store().currentUser?store().currentUser():null; }catch(e){ return null; } }
  function viewedUser(){ var q=new URLSearchParams(location.search).get('u'); if(q&&store()&&store().getUserByUsername){ var found=store().getUserByUsername(q); if(found) return found; } return me(); }
  function isOwn(u){ var self=me(); return !!(self&&u&&self.id&&u.id&&self.id===u.id); }
  function userPosts(u){ if(!u) return []; var list=[]; try{ if(store()&&store().postsByUser) list=store().postsByUser(u.id)||[]; }catch(e){} if(!list.length&&store()&&store().listPosts){ list=(store().listPosts()||[]).filter(function(p){ return (p.authorId&&p.authorId===u.id)||p.author===u.name||p.author===u.username; }); } return list.filter(function(p){ return mediaOf(p)||videoOf(p); }); }
  function paintTools(u,own){ var box=document.getElementById('pfTools'); if(!box) return; if(!u){ box.innerHTML='<button class="pf-btn on" type="button" data-pf="settings">Sign in</button>'; return; } if(own){ box.innerHTML='<button class="pf-btn" type="button" data-pf="edit">Edit profile</button><button class="pf-btn" type="button" data-pf="share">Share</button>'; return; } var following=store()&&store().isFollowing&&store().isFollowing(u.id); box.innerHTML='<button class="pf-btn '+(following?'':'on')+'" type="button" data-pf="follow">'+(following?'Following':'Follow')+'</button><button class="pf-btn" type="button" data-pf="message">Message</button>'; }
  function paintTags(u){ var box=document.getElementById('pfTags'); if(!box) return; var bits=[]; if(u&&u.role) bits.push(u.role); if(u&&u.classYear) bits.push(u.classYear); if(u&&u.org) bits.push(u.org); if(u&&u.house) bits.push(u.house); box.innerHTML=bits.map(function(t){ return '<span>'+esc(t)+'</span>'; }).join(''); box.hidden=!bits.length; }
  function paintHighs(posts){ var box=document.getElementById('pfHighs'); if(!box) return; var icons={events:'fa-calendar-day',sports:'fa-futbol',clubs:'fa-users',academics:'fa-book',graduation:'fa-user-graduate',music:'fa-music',arts:'fa-palette'}; var cats=[]; posts.forEach(function(p){ var c=String(p.category||p.classTag||'').toLowerCase(); if(c&&cats.indexOf(c)===-1) cats.push(c); }); if(!cats.length){ box.hidden=true; box.innerHTML=''; return; } box.hidden=false; box.innerHTML=cats.slice(0,8).map(function(c){ return '<button class="pf-hl" type="button" data-hl="'+esc(c)+'"><i class="fas '+(icons[c]||'fa-circle')+'"></i><span>'+esc(c)+'</span></button>'; }).join(''); }
  function emptyHtml(kind,own){ if(kind==='tagged') return '<div class="pf-empty"><i class="far fa-user"></i><strong>No tagged posts</strong></div>'; if(kind==='saved') return '<div class="pf-empty"><i class="far fa-bookmark"></i><strong>Nothing saved yet</strong></div>'; if(own) return '<div class="pf-empty"><i class="far fa-camera"></i><strong>Share your first moment</strong><button type="button" data-pf="create">Share a moment</button></div>'; return '<div class="pf-empty"><i class="far fa-images"></i><strong>No posts yet</strong></div>'; }
  function paintGrid(posts,own){ var grid=document.getElementById('pfGrid'); if(!grid) return; var list=posts.slice(); if(tab==='tagged') list=[]; if(tab==='saved'){ var ids=[]; try{ if(store()&&store().listSaved) ids=store().listSaved()||[]; }catch(e){} var all=[]; try{ if(store()&&store().listPosts) all=store().listPosts()||[]; }catch(e){} list=all.filter(function(p){ return ids.indexOf(p.id)!==-1&&(mediaOf(p)||videoOf(p)); }); } if(!list.length){ grid.innerHTML=emptyHtml(tab,own); grid._posts=[]; return; } grid.innerHTML=list.map(function(p,i){ var src=mediaOf(p); return '<button class="pf-cell" type="button" data-open="'+i+'">'+(src?'<img src="'+esc(src)+'" alt="'+esc(p.title||'Post')+'" loading="lazy">':'')+(isVideo(p)?'<i class="fas fa-play mark"></i>':'')+'</button>'; }).join(''); grid._posts=list; }
  function openModal(post){ var box=document.getElementById('pfModal'), stage=document.getElementById('pfModalStage'), cap=document.getElementById('pfModalCap'); if(!box||!post) return; box.hidden=false; var src=mediaOf(post), vid=videoOf(post); stage.innerHTML=(isVideo(post)&&vid)?'<video src="'+esc(vid)+'" poster="'+esc(src)+'" controls autoplay playsinline></video>':(src?'<img src="'+esc(src)+'" alt="">':''); cap.textContent=post.title||post.description||''; }
  function paint(){ var u=viewedUser(); var own=isOwn(u); var posts=userPosts(u); var counts={followers:0,following:0}; try{ if(u&&store()&&store().followCounts) counts=store().followCounts(u.id)||counts; }catch(e){} document.getElementById('pfHandle').textContent=(u&&u.username)||'profile'; document.getElementById('pfName').textContent=(u&&(u.name||u.displayName))||'Guest'; document.getElementById('pfRole').textContent=(u&&u.role)||''; document.getElementById('pfUser').textContent=u&&u.username?('@'+u.username):''; document.getElementById('pfBio').textContent=(u&&u.bio)||(own?'Add a short bio.':''); document.getElementById('pfPosts').textContent=abbr(posts.length); document.getElementById('pfFollowers').textContent=abbr(counts.followers||0); document.getElementById('pfFollowing').textContent=abbr(counts.following||0); var img=document.getElementById('pfAvaImg'); var photo=u&&(u.avatar||u.photoURL||u.profilePhoto); document.getElementById('pfAvaFall').textContent=String((u&&u.name)||'?').charAt(0).toUpperCase(); if(photo){ img.onload=function(){ img.style.display='block'; }; img.onerror=function(){ img.removeAttribute('src'); img.style.display='none'; }; img.src=photo; } else { img.removeAttribute('src'); img.style.display='none'; } paintTools(u,own); paintTags(u); paintHighs(posts); document.querySelectorAll('.pf-tabs button').forEach(function(b){ b.classList.toggle('on', b.dataset.tab===tab); }); paintGrid(posts,own); }
  function bind(){ if(g.__hshsProfileEvents) return; g.__hshsProfileEvents=true;
    document.addEventListener('click',function(e){ if(!isPage()) return; var pop=document.getElementById('pfPop'); var t=e.target.closest('[data-pf],[data-tab],[data-open]'); if(!t){ if(pop) pop.hidden=true; if(e.target.id==='pfEdit') document.getElementById('pfEdit').hidden=true; return; } if(t.dataset.open!=null){ openModal((document.getElementById('pfGrid')._posts||[])[Number(t.dataset.open)]); return; } if(t.dataset.tab){ tab=t.dataset.tab; paint(); return; } var act=t.dataset.pf; var u=viewedUser(); if(act==='menu'){ if(pop) pop.hidden=!pop.hidden; return; } if(pop) pop.hidden=true; if(act==='create'){ if(g.__hshsOpenUpload) g.__hshsOpenUpload(); return; } if(act==='settings'){ location.href=base()+'index/settings.html'; return; } if(act==='message'){ location.href=base()+'index/chat.html'; return; } if(act==='refresh'){ paint(); return; } if(act==='switch'){ var next=prompt('Open a username',(u&&u.username)||''); if(next) location.href=base()+'index/profile.html?u='+encodeURIComponent(next.replace(/^@/,'')); return; } if(act==='edit'){ if(!u) return; document.getElementById('pfEditName').value=u.name||''; document.getElementById('pfEditUser').value=u.username||''; document.getElementById('pfEditBio').value=u.bio||''; document.getElementById('pfEdit').hidden=false; return; } if(act==='close-edit'){ document.getElementById('pfEdit').hidden=true; return; } if(act==='save-edit'){ if(store()&&store().updateProfile&&me()) store().updateProfile({ name:document.getElementById('pfEditName').value.trim(), username:document.getElementById('pfEditUser').value.trim(), bio:document.getElementById('pfEditBio').value.trim() }); document.getElementById('pfEdit').hidden=true; paint(); return; } if(act==='share'){ if(navigator.share) navigator.share({ title:(u&&u.name)||'Profile', url:location.href }).catch(function(){}); else navigator.clipboard.writeText(location.href); return; } if(act==='follow'&&u&&store()&&store().toggleFollow){ store().toggleFollow(u.id); paint(); return; } if(act==='close-modal'){ document.getElementById('pfModal').hidden=true; document.getElementById('pfModalStage').innerHTML=''; } });
    document.addEventListener('keydown',function(e){ if(!isPage()||e.key!=='Escape') return; document.getElementById('pfModal').hidden=true; document.getElementById('pfEdit').hidden=true; document.getElementById('pfPop').hidden=true; });
  }
  function mount(){ if(!isPage()||!g.HshsRender||!g.HshsTemplates||!g.HshsTemplates.profile) return; if(g.HshsShell) try{ g.HshsShell.ensureShell(); }catch(e){} var root=document.getElementById('hshs-page'); if(!root){ root=document.createElement('div'); root.id='hshs-page'; document.body.appendChild(root); } loadCss(); g.HshsRender.mountHTML(root,g.HshsTemplates.profile); document.documentElement.setAttribute('data-hshs-page',PAGE); bind(); paint(); }
  function boot(){ var go=function(){ if(!isPage()) return; if(!g.HshsRender){ setTimeout(go,40); return; } mount(); }; if(g.HshsApp&&g.HshsApp.whenReady) g.HshsApp.whenReady(go); else document.addEventListener('hshs:foundation-ready',go,{once:true}); document.addEventListener('hshs:page',function(){ if(isPage()) setTimeout(go,0); }); }
  g.HshsProfile={ mount:mount };
  if(document.readyState==='loading') document.addEventListener('DOMContentLoaded',boot,{once:true}); else boot();
})(typeof window!=='undefined'?window:this);
