(function (g) {
  'use strict';
  if (g.__hshsProfilePageModule) return;
  g.__hshsProfilePageModule = true;
  var PAGE = 'profile';
  var tab = 'grid';
  var CAMPUS_PICS = [
    'https://images.unsplash.com/photo-1562774053-701939374585?auto=format&fit=crop&w=800&q=70',
    'https://images.unsplash.com/photo-1541339906-3e147b925338?auto=format&fit=crop&w=800&q=70',
    'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&w=800&q=70',
    'https://images.unsplash.com/photo-1577896851231-70ef18881754?auto=format&fit=crop&w=800&q=70',
    'https://images.unsplash.com/photo-1461896836934-ffe607ba6851?auto=format&fit=crop&w=800&q=70',
    'https://images.unsplash.com/photo-1523580846011-d3a5bc25702b?auto=format&fit=crop&w=800&q=70',
    'https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&w=800&q=70',
    'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=800&q=70',
    'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=800&q=70'
  ];
  var CAMPUS = { id:'hshs-world', name:'HSHS World', username:'hshs_world', role:'Hawthorne Scribner High School', bio:'Your school. One world.\nPhotos, Vibe and memories from Bududa Kikholo.', avatar: CAMPUS_PICS[2] };
  function isPage(){ try{ if(g.HshsRegistry&&HshsRegistry.activeRoute) return HshsRegistry.activeRoute().name===PAGE; }catch(e){} return (location.pathname.split('/').pop()||'').toLowerCase()==='profile.html'; }
  function base(){ return location.pathname.indexOf('/index/')!==-1?'../':''; }
  function esc(v){ return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];}); }
  function abbr(n){ n=Number(n)||0; if(n>=1000000) return (n/1000000).toFixed(1).replace('.0','')+'M'; if(n>=1000) return (n/1000).toFixed(1).replace('.0','')+'K'; return String(n); }
  function store(){ return g.HshsStore||null; }
  function me(){ try{ return store()&&store().currentUser?store().currentUser():null; }catch(e){ return null; } }
  function mediaOf(p){ return p.imageUrl||p.image_url||p.thumbnailUrl||p.thumbnail||p.image||p.cover||''; }
  function videoOf(p){ return p.videoUrl||p.video_url||''; }
  function isVideo(p){ return String(p.type||p.media_type||'').toLowerCase().indexOf('video')!==-1||!!videoOf(p); }
  function loadCss(){ if(document.querySelector('link[data-hshs-profile-css]')) return; var l=document.createElement('link'); l.rel='stylesheet'; l.href=base()+'css/hshs-profile.css?v=260907ig2'; l.setAttribute('data-hshs-profile-css','1'); document.head.appendChild(l); }
  function campusPack(){ var labels=['Sports Day','Assembly','Graduation','Campus walk','Track finals','Morning hall','Science fair','Lab hour','Friends']; var cats=['sports','events','graduation','campus','sports','events','academics','academics','clubs']; return CAMPUS_PICS.map(function(src,i){ return { id:'campus-'+i, title:labels[i], image:src, imageUrl:src, type:(i===3||i===4)?'video':'photo', category:cats[i], author:'HSHS World' }; }); }
  async function loadPosts(){ var out=[]; function push(list,type){ (list||[]).forEach(function(p){ var row=Object.assign({type:type||p.type},p); if(mediaOf(row)||videoOf(row)) out.push(row); }); } try{ if(g.db&&db.getPhotos) push(await db.getPhotos(48,0),'photo'); }catch(e){} try{ if(g.db&&db.getVideos) push(await db.getVideos(48,0),'video'); }catch(e){} try{ if(g.db&&db.getPosts) push(await db.getPosts(48,0)); }catch(e){} try{ if(store()&&store().listPosts) push(store().listPosts()); }catch(e){} var seen={}; out=out.filter(function(p){ var k=String(p.id||mediaOf(p)); if(seen[k]) return false; seen[k]=1; return true; }); if(!out.length) out=campusPack(); return out; }
  function viewedUser(){ var q=new URLSearchParams(location.search).get('u'); if(q&&store()&&store().getUserByUsername){ var found=store().getUserByUsername(q); if(found) return found; } return me()||CAMPUS; }
  function paintHighlights(posts){ var box=document.getElementById('igHighlights'); if(!box) return; var cats=[]; posts.forEach(function(p){ var c=String(p.category||p.classTag||'').toLowerCase(); if(c&&cats.indexOf(c)===-1) cats.push(c); }); if(!cats.length) cats=['sports','events','studio','campus']; box.innerHTML=cats.slice(0,6).map(function(c){ var post=posts.filter(function(p){ return String(p.category||'').toLowerCase()===c; })[0]||posts[0]; var src=post?mediaOf(post):CAMPUS_PICS[0]; return '<button class="ig-hl" type="button" data-hl="'+esc(c)+'"><b style="background-image:url(\''+esc(src)+'\')"></b><span>'+esc(c)+'</span></button>'; }).join(''); }
  function paintGrid(posts){ var grid=document.getElementById('igGrid'); if(!grid) return; var list=posts.slice(); if(tab==='reels') list=list.filter(isVideo); if(tab==='tagged') list=[]; if(tab==='saved'&&store()&&store().listSaved){ var ids=store().listSaved()||[]; list=posts.filter(function(p){ return ids.indexOf(p.id)!==-1; }); } if(!list.length){ grid.innerHTML='<div class="ig-empty"><i class="far fa-camera"></i><strong>No posts yet</strong></div>'; grid._posts=[]; return; } grid.innerHTML=list.map(function(p,i){ var src=mediaOf(p); var mark=isVideo(p)?'<i class="fas fa-play mark"></i>':''; return '<button class="ig-cell" type="button" data-open="'+i+'">'+(src?'<img src="'+esc(src)+'" alt="'+esc(p.title||'Post')+'">':'')+mark+'</button>'; }).join(''); grid._posts=list; }
  function openModal(post){ var box=document.getElementById('igModal'), stage=document.getElementById('igModalStage'), cap=document.getElementById('igModalCap'); if(!box||!post) return; box.hidden=false; var src=mediaOf(post), vid=videoOf(post); stage.innerHTML=(isVideo(post)&&vid)?'<video src="'+esc(vid)+'" poster="'+esc(src)+'" controls autoplay playsinline></video>':'<img src="'+esc(src)+'" alt="">'; cap.textContent=post.title||post.description||''; }
  async function paint(){ var u=viewedUser(); var posts=await loadPosts(); var counts=(u&&u.id&&store()&&store().followCounts)?store().followCounts(u.id):{followers:128,following:24}; if(!counts.followers) counts.followers=Math.max(posts.length*7,48); if(!counts.following) counts.following=18; document.getElementById('igUsername').textContent=u.username||'hshs_world'; document.getElementById('igName').textContent=u.name||u.displayName||'HSHS World'; document.getElementById('igRole').textContent=u.role||u.classYear||'Hawthorne Scribner High School'; document.getElementById('igBio').textContent=u.bio||CAMPUS.bio; document.getElementById('igPosts').textContent=abbr(posts.length); document.getElementById('igFollowers').textContent=abbr(counts.followers); document.getElementById('igFollowing').textContent=abbr(counts.following); var img=document.getElementById('igAvatar'); var photo=u.avatar||u.photoURL||u.profilePhoto||CAMPUS.avatar; img.alt=''; img.onload=function(){ img.style.opacity='1'; }; img.onerror=function(){ img.removeAttribute('src'); img.style.opacity='0'; }; img.src=photo; document.getElementById('igAvatarFall').textContent=String(u.name||'H').charAt(0).toUpperCase(); var own=!u.id||u.id===CAMPUS.id||(me()&&me().id===u.id); var actions=document.getElementById('igActions'); if(own) actions.innerHTML='<button class="ig-btn" type="button" data-ig="edit">Edit profile</button><button class="ig-btn" type="button" data-ig="share">Share profile</button><button class="ig-btn-sq" type="button" data-ig="refresh"><i class="fas fa-rotate"></i></button>'; else { var on=store()&&store().isFollowing&&store().isFollowing(u.id); actions.innerHTML='<button class="ig-btn '+(on?'':'primary')+'" type="button" data-ig="follow">'+(on?'Following':'Follow')+'</button><button class="ig-btn" type="button" data-ig="message">Message</button><button class="ig-btn-sq" type="button" data-ig="refresh"><i class="fas fa-rotate"></i></button>'; } paintHighlights(posts); paintGrid(posts); }
  function bind(){ if(g.__hshsProfileEvents) return; g.__hshsProfileEvents=true;
    document.addEventListener('click',function(e){ if(!isPage()) return; var t=e.target.closest('[data-ig],[data-tab],[data-open],[data-hl]'); if(!t){ if(e.target.id==='igEditSheet') document.getElementById('igEditSheet').hidden=true; return; } if(t.dataset.open!=null){ openModal((document.getElementById('igGrid')._posts||[])[Number(t.dataset.open)]); return; } if(t.dataset.tab){ tab=t.dataset.tab; paint(); return; } if(t.dataset.hl){ tab='grid'; paint(); return; } var act=t.dataset.ig; var u=viewedUser(); if(act==='create'){ if(g.__hshsOpenUpload) g.__hshsOpenUpload(); return; } if(act==='menu'){ location.href=base()+'index/settings.html'; return; } if(act==='threads'||act==='message'){ location.href=base()+'index/chat.html'; return; } if(act==='accounts'){ var next=prompt('Open a username', u.username||'hshs_world'); if(next) location.href=base()+'index/profile.html?u='+encodeURIComponent(next.replace(/^@/,'')); return; } if(act==='edit'){ document.getElementById('igEditName').value=u.name||''; document.getElementById('igEditUser').value=u.username||''; document.getElementById('igEditBio').value=u.bio||''; document.getElementById('igEditSheet').hidden=false; return; } if(act==='close-edit'){ document.getElementById('igEditSheet').hidden=true; return; } if(act==='save-edit'){ if(store()&&store().updateProfile&&me()) store().updateProfile({ name:document.getElementById('igEditName').value.trim(), username:document.getElementById('igEditUser').value.trim(), bio:document.getElementById('igEditBio').value.trim() }); document.getElementById('igEditSheet').hidden=true; paint(); return; } if(act==='share'){ var url=location.href; if(navigator.share) navigator.share({ title:'HSHS World', url:url }).catch(function(){}); else navigator.clipboard.writeText(url); return; } if(act==='follow'&&u&&store()&&store().toggleFollow){ store().toggleFollow(u.id); paint(); return; } if(act==='refresh'){ paint(); return; } if(act==='close-modal'){ document.getElementById('igModal').hidden=true; document.getElementById('igModalStage').innerHTML=''; } });
    document.addEventListener('keydown',function(e){ if(!isPage()||e.key!=='Escape') return; document.getElementById('igModal').hidden=true; document.getElementById('igEditSheet').hidden=true; });
  }
  function mount(){ if(!isPage()||!g.HshsRender||!g.HshsTemplates||!g.HshsTemplates.profile) return; if(g.HshsShell) try{ g.HshsShell.ensureShell(); }catch(e){} var root=document.getElementById('hshs-page'); if(!root){ root=document.createElement('div'); root.id='hshs-page'; document.body.appendChild(root); } loadCss(); g.HshsRender.mountHTML(root, g.HshsTemplates.profile); document.documentElement.setAttribute('data-hshs-page', PAGE); bind(); paint(); }
  function boot(){ var go=function(){ if(!isPage()) return; if(!g.HshsRender){ setTimeout(go,40); return; } mount(); }; if(g.HshsApp&&g.HshsApp.whenReady) g.HshsApp.whenReady(go); else document.addEventListener('hshs:foundation-ready',go,{once:true}); document.addEventListener('hshs:page',function(){ if(isPage()) setTimeout(go,0); }); }
  g.HshsProfile={ mount:mount };
  if(document.readyState==='loading') document.addEventListener('DOMContentLoaded',boot,{once:true}); else boot();
})(typeof window!=='undefined'?window:this);
